groups:
  - name: alerts
    rules:
      - alert: HighCPU Utilization
        expr: 100 - (avg by (component, env, instance, job, name)(rate(node_cpu_seconds_total{mode="idle"}[1m]) * 100))>50
        for: 1m
        labels:
          severity: page
        annotations:
          summary: High request latency